### ISSUE TITLE
Add error handling to posting retrieval

### ISSUE THREAD

**Issue by ilkkalehtinen** [OpusCapita/posting#19]
-If posting doesn't exist, initialize grid with empty data
-Handle null values for netAmount & grossAmount

**Comment by pirttpi1** [comment]
-If posting doesn't exist, initialize grid with empty data  -> ok, there is 'GridNoItems, and question marks, but let's live with those for now.
-Handle null values for netAmount & grossAmount  -> ok, show them now empty. we'll check later, if there should be 0.00 at least.
