### ISSUE TITLE
Add "Posting difference" into .json

### ISSUE THREAD

**Issue by Aappo** [OpusCapita/posting#31]
The title "Posting difference" on the Posting tab should be added to the .json file, so it can be localized.

**Comment by pirttpi1** [comment]
Posting difference and 'No posting rows' should be there now. There's also the new field Line Id, which should be translated in Finnish.

**Comment by pirttpi1** [comment]
GridNoItems is not translated yet.

**Comment by Aappo** [comment]
I have translated "GridNoItems" as "Ei tiliöintirivejä". I don't know if the string is unused, or why isn't it translated in the program.

**Comment by pirttpi1** [comment]
This is ok now.
