### ISSUE TITLE
Add posting difference validation

### ISSUE THREAD

**Issue by ilkkalehtinen** [OpusCapita/posting#39]
-Dim 'Save' button if there is a posting difference
-Style 'Save' button

**Comment by pirttpi1** [comment]
It seems that Save button can't be used with firefox. Works with IE and Chrome.

**Comment by ilkkalehtinen** [comment]
This is a locale issue. I created another ticket #42 .

**Comment by pirttpi1** [comment]
When posting values don't match to the invoice amounts, user can't save the posting.
When values match, user can save.
