### ISSUE TITLE
Add Description field to posting item so that it could be automatically generated or manually entered/edited in posting control

### ISSUE THREAD

**Issue by TimoRiippa** [OpusCapita/posting#48]
For Invoices posting we need to have a description field visible in posting grid which have these possible values as auto-generated depending on the case for the first version (in a later phase there are rules behind to define which data is copied to description field by default):
1)  no invoice line items --> copy supplier name to posting item description field
2) invoice line items exists --> copy product name (short) + product id to posting item description field in this format 
product name short (product id)

Add this new field to be part of posting item because posting line items should normally always have this information. 

This new posting grid (UI) column should be the 2nd column in the grid (aftern line #).
Description field is editable text field in the UI.
This nvarchar field can be maximum 650 characters.

**Comment by TimoRiippa** [comment]
You don't need to implement yet for the October version the logic to get description from supplier/line item product information. We just need to make sure that demo data imports this with other posting item data.

**Comment by pirttpi1** [comment]
Description is added now.
